### ISSUE TITLE
utilizing the correlation matrix

### ISSUE THREAD

**Issue by jsdron** [aj-grant/navmix#2]
Hi Andrew,

In the code provided for the simulation data, I can see that the correlation matrix (`b_cor`) is used directly as `navmix()` input. Given that the input matrix is suggested to undergo both standardization and normalization (like what was done for`b_prop`), I am wondering if the `b_cor` matrix should undergo something similar? 

For reference, I did the following:
```
# R.version                      
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.0                         
year           2021                        
month          05                          
day            18                          
svn rev        80317                       
language       R                           
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen   

### Since my traits are highly correlated and determined in the same sample, I need to use the correlation matrix
corX <- cor(traits, method=c("spearman"))  # traits have undergone rank-based inverse normal transformation
b_cor = matrix(nrow = n_all, ncol = m) #n_all=number of variants, m=number of traits
for (j in 1:n_all){
    S1 = diag(se[j, ])
    S = S1 %*% corX %*% S1
    b_cor[j, ] = solve(sqrtm(S), bhat[j, ])
  }
nav_out_cor <- navmix(b_cor, ...) 

### I also created a b_prop matrix since I interpreted the paper as to say that the input should be standardized and normalized
# For every _Beta_ for each SNP x Trait combination, I divided by its SE. The results were stored in a matrix called b_std.
# To normalize, I used the code provided in the simulation example:
b_prop = navmix::row_norm(data.matrix(b_std))
# I noticed that b_prop is never used as input for navmix()... is that indeed correct? Otherwise, I would do:
nav_out_prop <- navmix(b_prop, ...)

# Only b_std and b_cor look to be used as navmix() input in the simulation code.
```

Please let me know if you require any clarification. To try and summarize my questions:
1) Does `b_cor` need to be standardized+normalized prior to using with `navmix()`?
2) Is `b_prop` supposed to be run with navmix()? 

Thanks!
Jacqueline

**Comment by aj-grant** [comment]
Hi Jacqueline,
Thanks for the question!
The navmix() function will do the normalisation for you - so it will take any input matrix and transform it so each row has norm 1.
However, standardization is not automatic, since it is a user choice as to whether you wish to standardize or not.
So:
1. b_cor is already standardized, and can be input straight into navmix()
2. Running navmix with b_prop or b_std should give exactly the same results (b_prop is created in the simulation script to use in the mclust function which is a comparison method)

Hope that helps, but please let me know if anything isn't clear or there are any other questions!

**Comment by jsdron** [comment]
Hi Andrew,
Thank you so much for your response! That is incredibly helpful and answers my questions :)
